write_files:
- content: |
    #!/bin/bash

    set -e
    set -x

    # Requirements

    ## Download and prepare rke2
    curl -o /usr/local/bin/rke2-install https://get.rke2.io
    chmod a+x /usr/local/bin/rke2-install
    INSTALL_RKE2_TYPE="agent" rke2-install

    ## Setup configuration
    mkdir -p /etc/rancher/rke2
    cat << EOF > /etc/rancher/rke2/config.yaml
    server: ${RKE2_CLUSTER_INITIAL_SERVER:-"https://k8s-001-rke2-server:9345"}
    token: ${RKE2_CLUSTER_TOKEN:-"rke2_cluster_token"}
    EOF

    ## Enable and start service
    systemctl enable --now rke2-agent.service
  owner: root:root
  path: /var/lib/cloud/bootstrap/setup-rke2-agent.sh
  permissions: '0755'

runcmd:
  - /var/lib/cloud/bootstrap/setup-rke2-agent.sh
